RF-790: Add brokerage types
RizeFinance/rize-js pull request #154
Opened 2021-12-30 16:59 UTC by RockinRonE

## Ticket
[- https://phunts.atlassian.net/browse/RIZE-...](https://gathering.atlassian.net/browse/RF-790?atlOrigin=eyJpIjoiN2Y3YmVlMTJhNDVlNDBiYjgzNmFmZTljMzY5NWRmOGYiLCJwIjoiaiJ9)

## Changes
- Updated the types for Synthetic Account to include Target Yield Account fields

2022-01-03 17:50 UTC, KramerJeff approved these changes
LGTM

2022-01-04 16:49 UTC, RockinRonE commented
> Did we run the generate docs command here?

I did not! Ran it now :) Thanks!

2022-01-06 23:23 UTC, ksalmon requested changes

2022-01-06 23:23 UTC, ksalmon commented on types/lib/core/typedefs/synthetic-account.typedefs.d.ts
> +    synthetic_account_category: 'general' | 'external' | 'plaid_external' | 'target_yield_account';
@rwhunley Is the naming of 'target_yield_account' changing? I know target yield and high yield are the same thing from our product perspective

2022-01-06 23:23 UTC, ksalmon commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
We don't use yarn in this project, only NPM. Please remove this file

2022-01-06 23:28 UTC, rwhunley commented on types/lib/core/typedefs/synthetic-account.typedefs.d.ts
> +    synthetic_account_category: 'general' | 'external' | 'plaid_external' | 'target_yield_account';
As far as I know `target_yield_account` will not change. I believe, short of certainty, that "high yield" was deprecated because it implies a "high" which may turn out not to be true.

2022-01-06 23:36 UTC, ksalmon commented on types/lib/core/typedefs/synthetic-account.typedefs.d.ts
> +    synthetic_account_category: 'general' | 'external' | 'plaid_external' | 'target_yield_account';
Cool! Thanks ray!

2022-01-11 16:47 UTC, ksalmon approved these changes
Remove the yarn.lock @RockinRonE. Merge away! Thanks for this!

2022-01-12 14:48 UTC, ksalmon approved these changes

2022-01-12 14:49 UTC, merged