RF-1068: Add new debit card endpoint and tests
RizeFinance/rize-js pull request #181
Opened 2022-02-24 19:16 UTC by RockinRonE

[Ticket](https://rizemoney.atlassian.net/jira/software/c/projects/RF/boards/26?modal=detail&selectedIssue=RF-1068)

Added these endpoints and tests:

1. getAccessTokenData
2. getVirtualCardImage
3. issuePhysicalCard

2022-02-24 19:19 UTC, RockinRonE commented
@ksalmon Check out that error...what should we do about that?

2022-02-25 19:35 UTC, KramerJeff commented on lib/core/debit-card.js
> +   async issuePhysicalCard(
Nitpick: Maybe we should have this be migrateToPhysicalCard? It sounds more consistent with the API docs to me.

2022-02-25 19:36 UTC, KramerJeff commented on test/core/debit-card.spec.js
> +    let accessTokenData = { config_id: 'configID', token: 'token' };
This can be a `const` since you are modifying the properties and not the object reference.

2022-02-25 19:36 UTC, KramerJeff submitted a review, later dismissed
Minor nitpicks but nothing blocking. Good work, Ronny!

2022-02-28 14:48 UTC, RockinRonE commented on lib/core/debit-card.js
> +   async issuePhysicalCard(
<img width="648" alt="Screen Shot 2022-02-28 at 8 48 18 AM" src="https://user-images.githubusercontent.com/8163241/156003341-0e883409-bef8-4eff-9b1d-963d133eff8d.png">
Ha, yeah I had the same thought. I saw #3 on this and that's why I changed it...

2022-02-28 14:49 UTC, RockinRonE commented on test/core/debit-card.spec.js
> +    let accessTokenData = { config_id: 'configID', token: 'token' };
I appreciate this nitpick :)

2022-02-28 14:52 UTC, RockinRonE commented
Nooooooooooooooo `Jest: "packages/admin-base/src" coverage threshold for branches (90%) not met: 89.21%`

2022-02-28 18:52 UTC, RockinRonE commented
🙌 @ksalmon

2022-02-28 19:01 UTC, ksalmon requested changes
Can you share a screen shot of these tests passing?

2022-02-28 19:01 UTC, ksalmon commented on lib/core/debit-card.js
> +    this._validateGetParams(uid);
Not a fan of how this reads. Please add separate methods for validations for the individual calls, I understand they may overlap but it's more explicit and keeps with patterns

2022-02-28 19:10 UTC, RockinRonE commented on lib/core/debit-card.js
> +    this._validateGetParams(uid);
@ksalmon Can I do something like `validateUidParam`?

2022-02-28 19:18 UTC, RockinRonE commented on .eslintrc
> -      "indent": ["error", 4],
I'll change it back. I really hate 4 space indent. It's not consistent with our other codebases, and it takes up a lot of space on my laptop screen.

2022-03-02 22:46 UTC, ksalmon requested changes

2022-03-02 22:46 UTC, ksalmon commented on lib/core/debit-card.js
> +     * Validates the parameters for the "unlock" method
Please include @param 's here for this @protected methods

2022-03-02 22:46 UTC, ksalmon commented on lib/core/debit-card.js
> +     * Validates the parameters for the "unlock" method
Also, this is not for the unlock method. Quit the copy pasta sir!

2022-03-02 22:46 UTC, ksalmon commented on lib/core/debit-card.js
> +    /**
Indentation here looks funky bit it might be github formatting

2022-03-02 22:46 UTC, ksalmon commented on lib/core/debit-card.js
> +        this._validateGetParams(uid);
Please have a validateMigrateVirtualCard method instead of using two other methods validation funks

2022-03-02 22:46 UTC, ksalmon commented on package.json
> +  "version": "1.4.3",
Close. Not how semantic versioning works. It would be "1.4.0"

2022-03-08 21:55 UTC, RockinRonE commented on test/core/document.spec.js
> +describe.skip('Document', () => {
Line 96, fetching docs with a query, doesn't return data. I believe it's because this is a new customer.

2022-03-09 17:09 UTC, rwhunley commented
> ## Update
> 
>     * Document tests are failing because a user doesn't have documents when first created (I believe). There's no data in the response.
> 
>     * At the moment, a virtual card img cannot be retrieved on sandbox. @ksalmon We'll have to figure out how to handle this (if we should)

@RockinRonE - I think I have resolved the virtual card retrieval problem. Sandbox is still pointed at the non-terraformed load balancer, and the redirect rule for this route had to be manually removed. You should now be able to retrieve the mocked card image via the endpoint.

2022-03-09 17:23 UTC, RockinRonE commented
> > ## Update
> > ```
> > * Created debit cards are returning null for `external_uid`, thus breaking tests. @rwhunley said he is looking into this.
> > ```
> 
> I have the work to fix this scheduled in the next BE sprint. If it's a hard block for you I can expedite it and do it now; let me know.

@rwhunley It's not a hard block. Thank you for asking!

2022-03-09 18:04 UTC, ksalmon requested changes

2022-03-09 18:04 UTC, ksalmon commented on lib/core/debit-card.js
> + * @typedef {import('./typedefs/common.typedefs').MigrateCard} MigrateCard
You are importing this type but not using it anywhere...

2022-03-09 18:04 UTC, ksalmon commented on lib/core/debit-card.js
> + * @typedef {import('./typedefs/debit-card.typedefs').DebitCardAccessToken} DebitCardAccessToken
I don't see DebitCardAccessToken anywhere in this file.... I see `DebitCardAccessTokenData`...

2022-03-21 17:37 UTC, RockinRonE commented
@ksalmon This should be good to go now.

2022-03-21 23:13 UTC, ksalmon requested changes

2022-03-21 23:13 UTC, ksalmon commented on test/core/customer.spec.js
> +
remove extra whitespace

2022-03-21 23:13 UTC, ksalmon commented on test/core/customer.spec.js
> +            updatedCustomer = updatedCustomerResponse;
Feels lazy, just replace

2022-03-21 23:13 UTC, ksalmon commented on test/core/document.spec.js
> +        // This hits our timeout, for now
If you are going to skip tests, please create a ticket in JIRA to add it back. Please ping this thread with the ticket and I'll resolve

2022-03-21 23:13 UTC, ksalmon commented on lib/core/debitCards/debit-card.js
> +        return Buffer.from(response.data, 'binary').toString('base64');
I love returning a base64 string from this! Well thought out @RockinRonE. I would say in the `@return` that it's a base64 however cause you are saying it's a JPEG which is not right

2022-03-22 13:46 UTC, RockinRonE commented on lib/core/debitCards/validators.js
> +        if (
You keep mentioning spacing. I'm just running `lint-fix` for the files. What exactly do you mean? I don't understand.

2022-03-22 13:50 UTC, RockinRonE commented on lib/rize.js
> +const DebitCardService = require('./core/debitCards/debit-card');
I didn't feel that this was all that drastic nor arbitrary. It gets quite difficult to work with so many lines of code. I'll go ahead and create that directory.

2022-03-22 14:19 UTC, ksalmon commented on test/core/document.spec.js
> +        // This hits our timeout, for now
Ok, I'll create a ticket to bring this back

2022-03-22 14:23 UTC, ksalmon commented on test/core/customer.spec.js
> +            updatedCustomer = updatedCustomerResponse;
I don't understand why we needed to change any of this. Can you explain?

2022-03-30 13:56 UTC, RockinRonE commented
@ksalmon @KramerJeff Could you all please review this PR? You will not be able to test the middleware PR without the updated SDK.

2022-03-30 14:00 UTC, ksalmon submitted a review, later dismissed
LGTM

2022-03-30 21:21 UTC, KramerJeff submitted a review, later dismissed
LGTM, Good job on the documentation 👍🏼 💯

2022-04-01 16:27 UTC, RockinRonE commented
https://user-images.githubusercontent.com/8163241/161303906-de629733-ffd7-4e2f-b479-dfaeb98b6a1b.mov
@ksalmon 
Tests pass for virtual card.

The thing is that I need a physical card program to ensure the physical card tests pass. I've tried a physical card program but then the compliance workflow doesn't pass.

For a physical card program, the debit card needs to be created.

2022-04-01 17:10 UTC, ksalmon approved these changes

2022-04-01 17:10 UTC, merged