[RF-1409] Add customer types
RizeFinance/rize-js pull request #242
Opened 2022-06-06 18:42 UTC by alyant34

## Ticket
- https://rizemoney.atlassian.net/browse/RF-1409

## Changes
- Add customer type and business name to the Customer object

2022-06-06 18:45 UTC, alyant34 commented
@ksalmon I am sure I will need to make additional changes, but I am not sure why all the checks were not run?

2022-06-07 15:32 UTC, ksalmon requested changes

2022-06-07 15:32 UTC, ksalmon commented on types/lib/core/customer.d.ts
> +    protected _validateUpdateParams(uid: string, email: string, details: CustomerDetails, customer_type?: string): void;
```suggestion
    protected _validateUpdateParams(uid: string, email: string, details: CustomerDetails, customer_type?: 'unaffiliated' | 'sole_proprietor'): void;
```

2022-06-07 15:32 UTC, ksalmon commented on types/lib/core/customer.d.ts
> +    protected _validateUpdateParams(uid: string, email: string, details: CustomerDetails, customer_type?: string): void;
I would create a type for this like `type CustomerType = 'unaffiliated' | 'sole_proprietor'`

2022-06-07 17:44 UTC, alyant34 commented on test/core/custodial-account.spec.js
>          it('Throws an error if "type" query parameter is invalid', () => {
I am not sure I know what you mean, I tested the customer_type query in the customer.spec.js file

2022-06-07 19:23 UTC, merged