RF-1216: Reintroduce skipped tests
RizeFinance/rize-js pull request #295
Opened 2022-09-12 21:48 UTC by KramerJeff

## Ticket
https://rizemoney.atlassian.net/browse/RF-1216

## Dependencies
- ...

## Changes
Reintroduces skipped tests - this includes:

Acknowledges a multiple compliance documents
Throws an error if electronic signing is required and "ip_address" is not supplied Throws an error if electronic signing is required and "user_name" is not supplied Creates a new plaid_external synthetic account
Retrieves the document list without query

## Pre-Test Plan
- ...

## Test Plan
1. Pull down this branch.
2. Run `npm run test`

2022-09-13 17:05 UTC, alyant34 approved these changes

2022-09-14 18:05 UTC, ksalmon requested changes
Fix eslint issues :)

2022-09-14 19:55 UTC, ksalmon submitted a review, later dismissed
Lovely, and thanks for the deprecated method warn.

please increment the package.json file by a patch. This is not changing any runtime code so no need for a minor upgrade

2022-09-14 20:31 UTC, alyant34 approved these changes

2022-09-14 20:39 UTC, ksalmon approved these changes
Looks great! Thanks for this!

2022-09-14 20:58 UTC, merged