feat:[RF-1766] added unlock_all_params to unlock endpoint
RizeFinance/rize-js pull request #298
Opened 2022-10-25 03:48 UTC by arturo-rize

## Ticket
- https://rizemoney.atlassian.net/browse/RF-1766

## Dependencies
- ...

## Changes
- Adds `unlock_all_secondary` to `PUT /customers/{uid}/unlock `
- Adds validation for only true and false

## Pre-Test Plan
- ...

## Test Plan
1. Pull down this branch.
2. Test scenario

2022-10-25 13:49 UTC, matthewmcgarvey commented on lib/core/customer.js
> +    async unlock(uid, unlockReason = null, unlock_all_secondary = null) {
Couldn't this be a bool instead of a string?

2022-10-31 13:34 UTC, matthewmcgarvey submitted a review, later dismissed

2022-10-31 15:20 UTC, arturo-rize commented on lib/core/customer.js
> +        if (unlock_all_secondary && ![true, false].includes(unlock_all_secondary)) {
Will change that, at the end of the day all we are doing in backend  to verify this param is `unlock_all_secondary: params.permit(:unlock_all_secondary)[:unlock_all_secondary] == "true"`

2022-10-31 15:46 UTC, matthewmcgarvey commented
Looks like specs are failing

2022-10-31 19:42 UTC, matthewmcgarvey approved these changes

2022-10-31 20:20 UTC, matthewmcgarvey requested changes
Only noticed two things since I'm starting to work in this repo myself. 

There's types/docs in `docs.md` and `types/lib/core/customer.d.ts` that need to be updated for this method.

2022-11-01 14:17 UTC, matthewmcgarvey approved these changes

2022-11-01 17:03 UTC, kevindolch approved these changes

2022-11-07 14:53 UTC, kaymancera approved these changes

2022-11-07 14:59 UTC, merged